language: node_js
node_js:
- iojs
- '7'
deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_776919ea4a4e_key -iv $encrypted_776919ea4a4e_iv
  -in deploy_rsa.enc -out deploy_rsa -d
