language: php
php:
  - '7.1'
  - hhvm # on Trusty only
  - nightly
  
matrix:
  allow_failures:
    - php: '7.1'
    - php: hhvm
    - php: nightly
  fast_finish: true  
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_776919ea4a4e_key -iv $encrypted_776919ea4a4e_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
